apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tatoonz/kustomize-101.git
    targetRevision: develop
    path: phase-final/overlays/sit
  destination:
    name: in-cluster
    namespace: sit
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
